(defun arrange-frame ()
  "这个功能用来实现整齐的排列每个emacs frame"
  (interactive)
  (let ((lst (tabsupport-frame-list))
        (first-x)
        (first-y)
        (last-x)
        (last-y))
    (when (> (length lst) 2)
      (setq lst (sort lst 'left<))
      (let ((first-frame (nth 0 lst)))
        (setq first-x (frame-parameter first-frame 'left))
        (setq first-y (frame-parameter first-frame 'top)))
      (let* ((last-index (1- (length lst)))
             (rightest-frame (nth last-index lst)))
        (setq last-x (frame-parameter rightest-frame 'left))
        (setq last-y (frame-parameter rightest-frame 'top)))
      (let ((i 0))
        (dolist (frame lst)
          (let ((d (/ (float i) (float (- (length lst) 1)))))
            (set-frame-position
             frame
             (round (+ first-x (* d (- last-x first-x))))
             (round (+ first-y (* d (- last-y first-y)))))
            (setq i (1+ i))))))))
